### ISSUE TITLE
Missing pandas and error with TKAgg within matplot

### ISSUE THREAD

**Issue by YanchunHe** [cdr30/RapidMoc#6]
Hi, thanks for sharing this nice tool package!

However, I found two issue before I can run this package:

1. missing the pandas package
2. error with the `TkAgg`:
```
Traceback (most recent call last):
  File "plot_rapid_regions.py", line 17, in <module>
    matplotlib.use("TkAgg")
  File "/nird/home/yanchun/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1171, in use
    plt.switch_backend(name)
  File "/nird/home/yanchun/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 284, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

The first can be easily fixed by install the `pandas`, and would you suggest how to fix the second issue? many thanks!

**Comment by cdr30** [comment]
what version of matplotlib/python etc are you using?  Have you tried updating matplotlib? It looks like the tkinter dependency is not available for some reason. A google search of the error message provides a number of suggested fixes but i can’t try them without reproducing the error.

**Comment by YanchunHe** [comment]
```bash
$ conda list
# packages in environment at /conda/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
brotlipy                  0.7.0           py38h27cfd23_1003
ca-certificates           2020.10.14                    0
certifi                   2020.6.20          pyhd3eb1b0_3
cffi                      1.14.3           py38h261ae71_2
chardet                   3.0.4           py38h06a4308_1003
conda                     4.9.2            py38h06a4308_0
conda-package-handling    1.7.2            py38h03888b9_0
cryptography              3.2.1            py38h3c74f83_1
idna                      2.10                       py_0
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
ncurses                   6.2                  he6710b0_1
openssl                   1.1.1h               h7b6447c_0
pip                       20.2.4           py38h06a4308_0
pycosat                   0.6.3            py38h7b6447c_1
pycparser                 2.20                       py_2
pyopenssl                 19.1.0             pyhd3eb1b0_1
pysocks                   1.7.1            py38h06a4308_0
python                    3.8.5                h7579374_1
readline                  8.0                  h7b6447c_0
requests                  2.24.0                     py_0
ruamel_yaml               0.15.87          py38h7b6447c_1
setuptools                50.3.1           py38h06a4308_1
six                       1.15.0           py38h06a4308_0
sqlite                    3.33.0               h62c20be_0
tk                        8.6.10               hbc83047_0
tqdm                      4.51.0             pyhd3eb1b0_0
urllib3                   1.25.11                    py_0
wheel                     0.35.1             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

```bash
$ pip3 list
Package                Version
---------------------- -------------------
ansi2html              1.5.2
brotlipy               0.7.0
certifi                2020.6.20
cffi                   1.14.3
cftime                 1.3.0
chardet                3.0.4
conda                  4.9.2
conda-package-handling 1.7.2
cryptography           3.2.1
cycler                 0.10.0
idna                   2.10
kiwisolver             1.3.1
matplotlib             3.3.3
netCDF4                1.5.5.1
numpy                  1.19.5
pandas                 1.2.0
Pillow                 8.1.0
pip                    20.2.4
pycosat                0.6.3
pycparser              2.20
pyOpenSSL              19.1.0
pyparsing              2.4.7
PySocks                1.7.1
python-dateutil        2.8.1
pytz                   2020.5
rapidmoc               0.0.0
requests               2.24.0
ruamel-yaml            0.15.87
scipy                  1.6.0
setuptools             50.3.1.post20201107
six                    1.15.0
tqdm                   4.51.0
urllib3                1.25.11
wheel                  0.35.1
```

The command I am using:
```log
$ python3 plot_rapid_regions.py ../etc/config.ini.organic ~/vvellvl.3000.nc --m regions.png
Traceback (most recent call last):
  File "plot_rapid_regions.py", line 17, in <module>
    matplotlib.use("TkAgg")
  File "/nird/home/yanchun/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1171, in use
    plt.switch_backend(name)
  File "/nird/home/yanchun/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 284, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running
```

**Comment by YanchunHe** [comment]
$ pip3 install python-tk --user
ERROR: Could not find a version that satisfies the requirement python-tk (from versions: none)
ERROR: No matching distribution found for python-tk

**Comment by cdr30** [comment]
I will try and reproduce the issue and find a fix. This may not be immediate as this is not sn immediate priority for me given current constraints on my time. 

However, it looks like you are using a more recent version of Matplotlib than when i last updated, which could be the issue. 

In the longer term I need a better way to specify the dependencies and versions that were tested. 

In the mean time i suggest you try some of the suggestions online. Or just clone the repository and create a clean conda environment and install the required dependencies from their (including matplotlib etc.). 



In the mean-time I suggest

**Comment by YanchunHe** [comment]
Thanks  for the suggestion! I will try to find a solution while waiting for your updates. No hurry! 
All the best,
Yanchun

**Comment by YanchunHe** [comment]
I find this is likely because the `python-tk` or `tkinter` is missing in the linux server I am using. I don't have root permission to install it.

The `plot_rapid_regions.py` can run on my local PC without problem.
